# Generated by Django 3.2.7 on 2021-09-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20210924_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('likey', models.IntegerField(default=0)),
            ],
        ),
    ]
