# Generated by Django 3.2.7 on 2021-09-24 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
